### ISSUE TITLE
loopLayout.setScaleAnimation(false) 程序闪退

### ISSUE THREAD

**Issue by ZHOUJJIN** [tokiii/RevealBanner#11]
loopLayout.setScaleAnimation(false);// 设置是否需要动画 
设置不需要动画，程序闪退
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.widget.ImageView.getContext()' on a null object reference
        at com.wikikii.revealbanner.BannerActivity$1.onLoadImageView(BannerActivity.java:90)
        at com.wikikii.bannerlib.banner.LoopAdapterWrapper.instantiateItem(LoopAdapterWrapper.java:71)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)

**Comment by tokiii** [comment]
已修复
