### ISSUE TITLE
不支持加载网络图片吗

### ISSUE THREAD

**Issue by qiangqiangs** [tokiii/RevealBanner#7]

**Comment by tokiii** [comment]
支持的，把里面的图片换成网络地址就好.

**Comment by ZHOUJJIN** [comment]
loopLayout.setScaleAnimation(false);// 设置是否需要动画
设置为false就闪退了
 java.lang.NullPointerException: Argument must not be null
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:31)
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:25)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:647)
        at com.wikikii.revealbanner.BannerActivity$1.onLoadImageView(BannerActivity.java:92)
        at com.wikikii.bannerlib.banner.LoopAdapterWrapper.instantiateItem(LoopAdapterWrapper.java:71)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
